# Generated by Django 4.1.3 on 2022-11-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Available_vegetables',
            field=models.CharField(choices=[('bringle', 'BRINGLE'), ('chilli', 'CHILLI'), ('onion', 'ONION'), ('cauliFlower', 'CAULIFLOWER'), ('Tomato', 'TOMATO'), ('potato', 'POTATO')], default='bringle', max_length=50),
        ),
    ]
