# Generated by Django 4.1.3 on 2022-11-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_billing_available_vegetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Available_vegetables',
            field=models.CharField(choices=[('bringle', '20'), ('chilli', 'CHILLI'), ('onion', 'ONION'), ('cauliFlower', 'CAULIFLOWER'), ('Tomato', 'TOMATO'), ('potato', 'POTATO')], default='1', max_length=50,blank=True,null=True),
        ),
    ]
