# Generated by Django 4.1.3 on 2022-11-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_billing_available_vegetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='Available_vegetables',
        ),
    ]
