# Generated by Django 4.1.3 on 2022-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_billing_available_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='item',
            field=models.IntegerField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='qty',
            field=models.IntegerField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
