# Generated by Django 4.1.3 on 2022-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_billing_item_billing_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='item',
            field=models.IntegerField(default='1', max_length=50),
        ),
    ]
