# Generated by Django 4.1.3 on 2022-11-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_billing_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='date',
        ),
        migrations.AddField(
            model_name='billing',
            name='address',
            field=models.CharField(default='dd', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='item',
            field=models.IntegerField(default='25', max_length=50),
        ),
    ]
