# Generated by Django 4.1.3 on 2022-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_billing_date_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='item',
            field=models.CharField(choices=[('0', '---select experience----'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='0', max_length=50),
        ),
    ]
